# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token a68416c3c1bbb0ab03b8c6598b6c640b9032c23c

{
  "title": "Окно 400 IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH  {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token a68416c3c1bbb0ab03b8c6598b6c640b9032c23c

{
  "title": "Окно 400 IKEA",
  "status": "CLOSED"
}

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###


# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after = 2022-12-13
Content-Type: application/json
